name: Docker Image Build

on:
  push:
    branches: [ "master" ]
    paths-ignore: ['README.md']
  pull_request:
    branches: [ "master" ]
    paths-ignore: ['README.md']

jobs:
  # Just build the image to see if there are any errors
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nyu-devops-base:$(date +%s)
